### PR TITLE
SF4 and php7 mods

### PR DESCRIPTION
**Pull request by w473**
Modification to make it work with php7 and symfony 4
NOT TESTED with previous versions

### CODE REVIEW

**Comment by redthor** [comment]
Thanks @w473 

We're running php7.1 here but we don't have your addition:
```
+    "config": {
+        "platform": {
+            "ext-mongo": "1.6.16"
+        }
```

We do have this in our main app `composer.json`:
```
    "provide" : {
        "ext-mongo": "*"
    },
```
perhaps that's all you need for php7?

Could you submit another PR with just the sf4 changes or change this one to have just sf4?

If you think we still need php7 changes, please submit another PR just for that so we can review separately.

Thanks again for helping.

**Comment by w473** [comment]
I will check this evening your suggestions. But to make it work I need info about ext-mongo for php7 and I need php7.1 for sf4

**Comment by w473** [comment]
So I've rechecked everything and it looks like its required to install mapper for old mongo lib:
alcaeus/mongo-php-adapter
so I updated readme file, and removed wrong composer.json entries

**Comment by caciobanu** [comment]
The build is failing because of this : **if [ "x${ADAPTER_VERSION}" != "x" ]; then composer require "alcaeus/mongo-php-adapter=${ADAPTER_VERSION}" --ignore-platform-reqs; fi**. We have to update the build script.

**Comment by redthor** [comment]
I've opened https://github.com/doesntmattr/mongodb-migrations/pull/14 to remove the php5.3 build error.

And then opened https://github.com/doesntmattr/mongodb-migrations/pull/15 to remove the php7.0 error.

The https://github.com/doesntmattr/mongodb-migrations/pull/15 build is passing but I've removed support for php7.0 and jumped to php7.1

If we go with those changes then we can see how this build is going after that.

**Comment by redthor** [comment]
@w473 do you mind just updating the PR with master so we can get the travis tests running, then we should be good to go

**Comment by w473** [comment]
still issues...:

> 5.3 is not pre-installed; installing
> Downloading archive: https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/12.04/x86_64/php-5.3.tar.bz2
> 370.45s$ curl -s -o archive.tar.bz2 $archive_url && tar xjf archive.tar.bz2 --directory /
> 0.00s
> 0.02s$ phpenv global 5.3
> rbenv: version `5.3' not installed
> The command "phpenv global 5.3" failed and exited with 1 during .

**Comment by caciobanu** [comment]
We should just ignore 5.3 and drop builds for it as Symfony 4 does not even install on PHP 5.3.

**Comment by w473** [comment]
well this should work with older version of symfony, but supporting now anything below php 5.6 is somehow strange for me

**Comment by redthor** [comment]
I've made release `1.2` that people on `php5.3` (if there are any!) can use (that build passed). 

We can merge this one into `master`.

Then we can remove `php5.3` and also look at removing `php5.*` and maybe `symfony 2.*`?

**Comment by redthor** [comment]
On merge this PR's build has passed

**Comment by redthor** [comment]
https://github.com/doesntmattr/mongodb-migrations/pull/16 opened to remove `php5.3` anyway

**Comment by redthor** [comment]
Thanks for helping @w473 

I've tagged a `1.2.1` release - can you try that out?

**Comment by w473** [comment]
thx, I will check it tomorrow

**Comment by w473** [comment]
works properly THX!

**Pull request merged**
